### ISSUE TITLE
What to set GO_INSTALL_PACKAGE_SPEC to?

### ISSUE THREAD

**Issue by ernsheong** [sendwithus/buildpack-go#1]
Sorry, this env var is not very Google-able... and I'm trying to use this for Flynn

**Comment by dlsteuer** [comment]
Hey @ernsheong we built this specifically for our golang project structure, which has all the code in a src directory. GO_INSTALL_PACKAGE_SPEC can be set to anything as long as it's set, and that becomes the package name for the code when heroku is building the project. So for example, we set ours to `github.com/sendwithus/<project name>`. We also include all of our vendored dependencies in source, so we don't require a tool for govendor to be run. There is also no guarantee that it won't change in the future as our project structure evolves. Basically use at your own risk.

**Comment by ernsheong** [comment]
Thanks for the clarification!
